import PDFKit
import XCTest

@testable import Clippy

/// CAP-02/04/05/08 and FEAT-01: what the monitor captures, skips, attributes, and counts.
final class CaptureMonitorPolicyTests: CaptureTestCase {

    // MARK: CAP-02: exact change count

    func testOwnWriteIsSkippedAndAForeignCopyRightAfterIsKept() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        write(pb, "seed")
        monitor.tick()
        XCTAssertNotNil(try clip(db, text: "seed"))

        monitor.performOwnWrite { write(pb, "clippy wrote this") }
        // A foreign copy lands before the next poll: it must not be swallowed.
        write(pb, "foreign copy")
        monitor.tick()
        XCTAssertNotNil(try clip(db, text: "foreign copy"), "a foreign copy in the window was lost")
        XCTAssertFalse(try hasClip(db, text: "clippy wrote this"))
    }

    func testOwnWriteAloneIsNotRecapturedAndLaterCopiesStillAre() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        write(pb, "seed")
        monitor.tick()
        XCTAssertNotNil(try clip(db, text: "seed"))

        monitor.performOwnWrite { write(pb, "own") }
        monitor.tick()
        XCTAssertFalse(try hasClip(db, text: "own"))

        write(pb, "next foreign")
        monitor.tick()
        XCTAssertNotNil(try clip(db, text: "next foreign"))
    }

    func testAWriteThatChangedNothingRegistersNothing() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        write(pb, "seed")
        monitor.tick()
        XCTAssertNotNil(try clip(db, text: "seed"))

        monitor.performOwnWrite { /* failed write: no change */ }
        write(pb, "foreign after failed own write")
        monitor.tick()
        XCTAssertNotNil(try clip(db, text: "foreign after failed own write"))
    }

    // MARK: FEAT-01: concealed / transient / legacy markers, blocklist

    func testMarkerTypesAreNeverCaptured() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        let markers = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                       "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
                       "de.petermaurer.TransientPasteboardType", "Pasteboard generator type"]
        for (index, marker) in markers.enumerated() {
            let text = "hidden \(index)"
            pb.clearContents()
            pb.setString(text, forType: .string)
            pb.setString("", forType: NSPasteboard.PasteboardType(marker))
            monitor.tick()
            XCTAssertFalse(try hasClip(db, text: text, timeout: 0.3), "\(marker) must be skipped")
        }
        write(pb, "visible")
        monitor.tick()
        XCTAssertNotNil(try clip(db, text: "visible"), "a skip must not wedge the monitor")
    }

    func testShouldSkipHonorsBlocklistEqualityAndConformance() {
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: ["public.html"], blocklist: ["public.html"]))
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: ["public.utf8-plain-text"], blocklist: ["public.text"]),
                      "conforming types are blocked")
        XCTAssertFalse(ClipboardMonitor.shouldSkip(types: ["public.png"], blocklist: ["public.text"]))
        XCTAssertFalse(ClipboardMonitor.shouldSkip(types: ["public.utf8-plain-text"], blocklist: []))
        XCTAssertTrue(ClipboardMonitor.shouldSkip(types: ["org.nspasteboard.ConcealedType"], blocklist: []))
    }

    func testBlocklistedTypeStopsCapture() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        CapturePreferences.typeBlocklist = ["public.html"]
        pb.clearContents()
        pb.setString("with html", forType: .string)
        pb.setString("<b>with html</b>", forType: .html)
        monitor.tick()
        XCTAssertFalse(try hasClip(db, text: "with html", timeout: 0.3))
    }

    // MARK: CAP-04: source attribution

    func testPasteboardSourceHintWinsOverActivationHistory() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let tracker = SourceAppTracker(notificationCenter: NotificationCenter(), ownBundleID: "com.example.clippy", seedFromFrontmost: false)
        tracker.record(bundleID: "com.example.frontmost", name: "Front", at: Date().addingTimeInterval(-10))
        let monitor = ClipboardMonitor(database: db, pasteboard: pb, sourceTracker: tracker)
        pb.clearContents()
        pb.setString("hinted copy", forType: .string)
        pb.setString("com.example.copier", forType: SourceAppTracker.sourceType)
        monitor.tick()
        XCTAssertEqual(try clip(db, text: "hinted copy")?.sourceAppBundleID, "com.example.copier")
    }

    func testActivationHistoryIsTheFallbackAndIgnoreListSeesEveryCandidate() throws {
        let tracker = SourceAppTracker(notificationCenter: NotificationCenter(), ownBundleID: "com.example.clippy", seedFromFrontmost: false)
        let base = Date()
        tracker.record(bundleID: "com.example.a", name: "A", at: base.addingTimeInterval(-30))
        tracker.record(bundleID: "com.example.b", name: "B", at: base.addingTimeInterval(-1))
        tracker.record(bundleID: "com.example.clippy", name: "Clippy", at: base.addingTimeInterval(-0.5))

        XCTAssertEqual(tracker.app(at: base.addingTimeInterval(-20))?.bundleID, "com.example.a")
        XCTAssertEqual(tracker.lastExternalApp?.bundleID, "com.example.b", "Clippy's own activation is not recorded")
        // Window straddles the A -> B switch: both are plausible sources.
        let straddling = tracker.candidates(since: base.addingTimeInterval(-2), now: base)
        XCTAssertEqual(straddling.map(\.bundleID), ["com.example.a", "com.example.b"])
        // Window entirely after B: only B.
        XCTAssertEqual(tracker.candidates(since: base.addingTimeInterval(-0.9), now: base).map(\.bundleID), ["com.example.b"])
    }

    func testCopyStraddlingAnAppSwitchIsSkippedWhenEitherAppIsIgnored() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let tracker = SourceAppTracker(notificationCenter: NotificationCenter(), ownBundleID: "com.example.clippy", seedFromFrontmost: false)
        let monitor = ClipboardMonitor(database: db, pasteboard: pb, sourceTracker: tracker)
        let settings = AppSettings.shared
        let savedIgnored = settings.ignoredBundleIDs
        settings.ignoredBundleIDs = ["com.example.vault"]
        addTeardownBlock { settings.ignoredBundleIDs = savedIgnored }

        monitor.tick()  // establishes the poll window
        tracker.record(bundleID: "com.example.vault", name: "Vault", at: Date().addingTimeInterval(-0.02))
        tracker.record(bundleID: "com.example.editor", name: "Editor", at: Date())
        write(pb, "copied from the vault")
        monitor.tick()
        XCTAssertFalse(try hasClip(db, text: "copied from the vault", timeout: 0.3))
    }

    // MARK: CAP-05: failure counter

    func testTotalFileCaptureFailureIsCountedAndRetriedNotLost() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("clippy-cap-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let file = dir.appendingPathComponent("unreadable.txt")
        try Data("secret".utf8).write(to: file)
        try FileManager.default.setAttributes([.posixPermissions: 0o000], ofItemAtPath: file.path)
        addTeardownBlock {
            try? FileManager.default.setAttributes([.posixPermissions: 0o644], ofItemAtPath: file.path)
            try? FileManager.default.removeItem(at: dir)
        }
        pb.clearContents()
        XCTAssertTrue(pb.writeObjects([file as NSURL]))
        monitor.tick()
        XCTAssertTrue(waitFor { monitor.failureCount >= 1 }, "the failure must reach the published counter")
        XCTAssertNotNil(monitor.lastFailure)
        XCTAssertFalse(monitor.lastFailure?.contains("unreadable") ?? false, "file names are not surfaced")

        // The retry re-runs the capture on the next polls, up to its limit.
        for _ in 0..<6 {
            monitor.tick()
            RunLoop.current.run(until: Date().addingTimeInterval(0.15))
        }
        XCTAssertGreaterThanOrEqual(monitor.failureCount, 2)
        XCTAssertLessThanOrEqual(monitor.failureCount, 3, "retries are bounded")
        XCTAssertTrue(monitor.consecutiveFailures >= 2)
        XCTAssertFalse(monitor.hasRepeatedFailures && monitor.consecutiveFailures < ClipboardMonitor.repeatedFailureThreshold)
    }

    // MARK: CAP-08: launch capture, auto-clear, merge, profiles

    func testCaptureOnLaunchIsOptIn() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        write(pb, "already there")
        let off = makeMonitor(db, pb)
        off.start()
        off.tick()
        XCTAssertFalse(try hasClip(db, text: "already there", timeout: 0.3))

        CapturePreferences.captureOnLaunch = true
        let db2 = try makeTestDatabase(self)
        let on = makeMonitor(db2, pb)
        on.start()
        on.tick()
        XCTAssertNotNil(try clip(db2, text: "already there"))
    }

    func testSensitiveCaptureIsFlaggedAndAutoClearedWithANotification() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        var notices: [(String, String)] = []
        monitor.autoClearNotifier = { notices.append(($0, $1)) }
        CapturePreferences.sensitiveAutoClearSeconds = 0  // scheduled explicitly below

        let card = "4111 1111 1111 1111"
        write(pb, card)
        monitor.tick()
        let saved = try XCTUnwrap(try clip(db, text: card))
        let store = SensitiveFlagStore(directory: db.media.sidecarDirectory)
        XCTAssertEqual(store.entry(for: saved.contentKey)?.kinds, [.creditCard])
        XCTAssertTrue(SensitiveContent.isSensitive(clip: saved, store: store))

        monitor.scheduleAutoClear(changeCount: pb.changeCount, clipID: saved.id, key: saved.contentKey, after: 0.05)
        XCTAssertTrue(waitFor { !notices.isEmpty })
        XCTAssertNil(pb.string(forType: .string), "clipboard cleared")
        XCTAssertNil(try db.allClips().first { $0.id == saved.id }, "history row deleted")
        XCTAssertFalse(notices[0].1.contains("4111"), "notifications carry no clip content")
        // The clear was Clippy's own write: it is not recaptured.
        monitor.tick()
        XCTAssertEqual(try db.allClips().count, 0)
    }

    func testAutoClearLeavesAChangedClipboardAlone() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        var notices = 0
        monitor.autoClearNotifier = { _, _ in notices += 1 }
        write(pb, "4111111111111111")
        monitor.tick()
        let saved = try XCTUnwrap(try clip(db, text: "4111111111111111"))
        let capturedCount = pb.changeCount
        write(pb, "user copied something else")

        CapturePreferences.autoClearDeletesHistory = false
        monitor.scheduleAutoClear(changeCount: capturedCount, clipID: saved.id, key: saved.contentKey, after: 0.05)
        RunLoop.current.run(until: Date().addingTimeInterval(0.3))
        XCTAssertEqual(pb.string(forType: .string), "user copied something else")
        XCTAssertEqual(notices, 0)
        XCTAssertNotNil(try db.allClips().first { $0.id == saved.id })
    }

    func testMergeAndAppend() throws {
        let db = try makeTestDatabase(self)
        var image = makeTextClip("")
        image.contentKind = .image
        let clips = [makeTextClip("one"), image, makeTextClip("  "), makeTextClip("two")]
        XCTAssertEqual(ClipMerge.mergedText(clips), "one\ntwo")
        XCTAssertEqual(ClipMerge.mergedText(clips, separator: ", "), "one, two")
        XCTAssertNil(ClipMerge.mergedText([image]))

        let id = try XCTUnwrap(try ClipMerge.saveMerged(clips, into: db))
        XCTAssertEqual(try db.allClips().first { $0.id == id }?.contentText, "one\ntwo")
        XCTAssertNil(try ClipMerge.saveMerged([image], into: db))

        var base = try XCTUnwrap(try db.allClips().first { $0.id == id })
        XCTAssertTrue(try ClipMerge.append("three", to: base, in: db))
        base = try XCTUnwrap(try db.allClips().first { $0.id == id })
        XCTAssertEqual(base.contentText, "one\ntwo\nthree")
        XCTAssertFalse(try ClipMerge.append("  ", to: base, in: db))
        XCTAssertFalse(try ClipMerge.append("x", to: image, in: db))
    }

    func testPasteProfilesDefaultTerminalsToPlainAndHonorOverrides() {
        XCTAssertEqual(PasteProfiles.mode(forBundleID: "com.apple.Terminal"), .plainText)
        XCTAssertEqual(PasteProfiles.mode(forBundleID: "com.microsoft.VSCode"), .plainText)
        XCTAssertEqual(PasteProfiles.mode(forBundleID: "com.apple.Notes"), .automatic)
        XCTAssertTrue(PasteProfiles.shouldPastePlain(bundleID: "com.apple.Terminal", callerAsksPlain: false))
        XCTAssertFalse(PasteProfiles.shouldPastePlain(bundleID: "com.apple.Notes", callerAsksPlain: false))
        XCTAssertTrue(PasteProfiles.shouldPastePlain(bundleID: "com.apple.Notes", callerAsksPlain: true))
        XCTAssertFalse(PasteProfiles.shouldPastePlain(bundleID: nil, callerAsksPlain: false))

        PasteProfiles.setMode(.rich, forBundleID: "com.apple.Terminal")
        XCTAssertFalse(PasteProfiles.shouldPastePlain(bundleID: "com.apple.Terminal", callerAsksPlain: true), "override beats the built-in")
        PasteProfiles.setMode(.plainText, forBundleID: "com.apple.Notes")
        XCTAssertTrue(PasteProfiles.shouldPastePlain(bundleID: "com.apple.Notes", callerAsksPlain: false))
        PasteProfiles.setMode(.automatic, forBundleID: "com.apple.Terminal")
        XCTAssertEqual(PasteProfiles.mode(forBundleID: "com.apple.Terminal"), .plainText, "clearing restores the built-in")
    }

    func testRichTextIsPastedPlainIntoATerminal() throws {
        let db = try makeTestDatabase(self)
        let pb = makePasteboard()
        let monitor = makeMonitor(db, pb)
        var rich = makeTextClip("styled")
        rich.contentRTF = Data("{\\rtf1 styled}".utf8)
        let service = PasteService(monitor: monitor, sendKeystroke: { _ in true }, frontmostBundleID: { "com.apple.Terminal" })
        let done = expectation(description: "paste")
        service.paste(rich, asPlainText: false) { _ in done.fulfill() }
        wait(for: [done], timeout: 5)
        XCTAssertEqual(pb.string(forType: .string), "styled")
        XCTAssertNil(pb.data(forType: .rtf))
    }
}
