import AppKit
import Combine

extension Notification.Name {
    /// Posted on the main thread immediately after a clip is saved, at the same
    /// instant the capture sound fires. The status item observes it to bounce
    /// the mascot in sync with the sound.
    static let clippyDidCapture = Notification.Name("ClippyDidCapture")
}

/// Watches NSPasteboard.general by polling changeCount (the only supported
/// detection mechanism on macOS) and stores new items.
final class ClipboardMonitor {
    private let database: ClipDatabase
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount = 0
    private var skipNextChange = false
    private var cancellables = Set<AnyCancellable>()

    /// The changeCount of a pasteboard write we have seen but that had not been
    /// filled in yet, and when we first saw it. See tick().
    private var unresolvedChangeCount: Int?
    private var unresolvedSince = Date.distantPast

    /// How long a change may stay unresolved before it is retired anyway. Long
    /// enough for the slowest multi-flavor writers, short enough that a flavor
    /// we will never support cannot keep the poll re-reading the pasteboard.
    private static let unresolvedGrace: TimeInterval = 2.0

    /// Serial queue for the heavy capture work (DB write, FTS reindex, eviction,
    /// media file copy, thumbnail encoding). The poll timer fires on the main
    /// run loop, so doing this work inline froze the UI on every copy; under DB
    /// queue contention (e.g. a background iCloud export holding the shared
    /// DatabaseQueue) the main thread could stall until the write committed.
    /// The pasteboard is still read on the main thread (AppKit-affined), then
    /// the save is dispatched here. Serial to preserve capture order and keep
    /// concurrent evictions from racing on the shared DatabaseQueue.
    private let captureQueue = DispatchQueue(label: "com.bytesavvy.clippy.capture-save", qos: .userInitiated)

    var isPaused = false

    /// Pasteboard types that mean "do not record this". ConcealedType is the
    /// convention password managers (1Password, Bitwarden, ...) set on copied
    /// secrets; TransientType marks ephemeral writes.
    private static let skippedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// The pasteboard is injectable so the capture path can be driven headlessly
    /// in tests; production always watches the general pasteboard.
    init(database: ClipDatabase, pasteboard: NSPasteboard = .general) {
        self.database = database
        self.pasteboard = pasteboard
    }

    // MARK: - Timer and polling

    func start() {
        lastChangeCount = pasteboard.changeCount
        scheduleTimer()
        AppSettings.shared.$pollingIntervalMs
            .removeDuplicates()
            .dropFirst()
            .sink { [weak self] _ in self?.scheduleTimer() }
            .store(in: &cancellables)
    }

    /// Called right before Clippy writes the pasteboard itself, so its own
    /// paste does not get re-captured (keeps history order stable).
    func ignoreNextChange() {
        skipNextChange = true
    }

    private func scheduleTimer() {
        timer?.invalidate()
        let interval = max(0.05, AppSettings.shared.pollingIntervalMs / 1000.0)
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
        timer.tolerance = interval / 4
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// One poll. Internal rather than private so tests can drive the capture
    /// path deterministically instead of waiting on the timer.
    func tick() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }

        if skipNextChange {
            retire(changeCount)
            skipNextChange = false
            return
        }
        guard !isPaused else {
            retire(changeCount)
            return
        }

        // An app that writes several flavors bumps changeCount on
        // clearContents() and fills the data in up to a few hundred ms later.
        // Retiring the change on that first empty look loses the copy for good
        // (no clip, no mascot bounce, no capture sound) because the changeCount
        // never comes around again. Keep the change live until the pasteboard
        // resolves, or until the grace period expires.
        if captureCurrentPasteboard() {
            retire(changeCount)
        } else if unresolvedChangeCount != changeCount {
            unresolvedChangeCount = changeCount
            unresolvedSince = Date()
        } else if Date().timeIntervalSince(unresolvedSince) >= Self.unresolvedGrace {
            retire(changeCount)
        }
    }

    /// Marks a pasteboard change as dealt with so it is never looked at again.
    private func retire(_ changeCount: Int) {
        lastChangeCount = changeCount
        unresolvedChangeCount = nil
    }

    // MARK: - Text capture

    /// Returns true when this change is resolved: something was captured, or it
    /// was deliberately skipped. False means the pasteboard has not been filled
    /// in yet and the change deserves another look.
    ///
    /// Deliberate skips (concealed types, ignored source apps) MUST return true.
    /// Retrying one of those would re-read it after the frontmost app changed,
    /// which is how a password copy would end up in history.
    private func captureCurrentPasteboard() -> Bool {
        guard let types = pasteboard.types, !types.isEmpty else { return false }
        guard Self.skippedTypes.isDisjoint(with: Set(types)) else { return true }

        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier,
           AppSettings.shared.ignoredBundleIDs.contains(bundleID) {
            return true
        }

        // File URLs must be checked before the text path: Finder's copy puts
        // both a file URL and a display-name string on the pasteboard, and we
        // want the richer file clip, not a bare filename text clip.
        if captureFileIfPresent(from: frontApp) { return true }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            captureText(text, from: frontApp)
            return true
        }
        return captureImageIfPresent(from: frontApp)
    }

    private func captureText(_ text: String, from frontApp: NSRunningApplication?) {
        // Snapshot the pasteboard on the main thread (AppKit-affined), then
        // dispatch the DB write off-main so a copy never blocks the UI.
        let rtf = pasteboard.data(forType: .rtf)
        let html = pasteboard.data(forType: .html)
        let typeIdentifier: String
        if rtf != nil {
            typeIdentifier = "public.rtf"
        } else if html != nil {
            typeIdentifier = "public.html"
        } else {
            typeIdentifier = "public.utf8-plain-text"
        }
        let bundleID = frontApp?.bundleIdentifier
        let appName = frontApp?.localizedName
        let createdAt = Date()
        let cap = AppSettings.shared.maxHistoryItems
        let database = self.database

        captureQueue.async { [weak self] in
            var clip = Clip(
                id: nil,
                contentText: text,
                contentRTF: rtf,
                contentHTML: html,
                typeIdentifier: typeIdentifier,
                sourceAppBundleID: bundleID,
                sourceAppName: appName,
                createdAt: createdAt
            )
            do {
                try database.saveCapturedClip(&clip, cap: cap)
                let savedID = clip.id
                // Sound/title fire only after a confirmed save; duplicates or DB
                // errors get no feedback. Hop back to main for AppKit + the
                // .clippyDidCapture notification the status item observes.
                DispatchQueue.main.async { [weak self] in
                    self?.playCaptureSound()
                    self?.maybeAutoSuggestTitle(forText: text, clipID: savedID)
                }
            } catch {
                ClippyLog.error("Failed to save clip: \(error)", category: ClippyLog.capture)
            }
        }
    }

    /// The one auto-applied agentic action: when enabled, give a freshly captured
    /// text clip an AI-suggested title. Opt-in, detached, and best-effort, so it
    /// never blocks or breaks capture; the title is still user-editable.
    private func maybeAutoSuggestTitle(forText text: String, clipID: Int64?) {
        let settings = AppSettings.shared
        guard settings.aiEnabled, settings.aiAutoSuggestTitles, let clipID else { return }
        guard case .success(let service) = AIService.fromSettings() else { return }
        let database = self.database
        Task.detached {
            // Title the exact row we just inserted. Re-finding by content text
            // could match a different clip when identical text was captured twice.
            guard let proposal = try? await service.suggestTitle(forText: text),
                  !proposal.proposed.isEmpty
            else { return }
            try? database.updateClipTitle(id: clipID, userTitle: proposal.proposed)
        }
    }

    // MARK: - File capture

    /// Returns true when at least one file clip was captured so the caller can
    /// skip text/image. Multi-file Finder selections are captured as one clip
    /// per file URL (mirroring how single-file clips are saved), so a Cmd+C of
    /// five files produces five file clips in history rather than silently
    /// keeping only the first URL.
    @discardableResult
    private func captureFileIfPresent(from frontApp: NSRunningApplication?) -> Bool {
        let settings = AppSettings.shared
        guard settings.captureFiles else { return false }

        let options: [NSPasteboard.ReadingOptionKey: Any] = [
            .urlReadingFileURLsOnly: true
        ]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options)
                as? [URL],
              !urls.isEmpty
        else { return false }

        // Filter out zero-byte / unreadable files up front so one bad file in a
        // multi-selection does not abort the whole capture. A single empty file
        // (the legacy behavior) still returns false here so the caller can fall
        // through to text/image capture.
        let viable = urls.filter { url in
            let attrs = try? FileManager.default.attributesOfItem(atPath: url.path)
            let size = (attrs?[.size] as? Int) ?? 0
            return size > 0
        }
        guard !viable.isEmpty else { return false }

        let thresholdBytes = settings.maxFileSizeMB * 1_000_000
        let bundleID = frontApp?.bundleIdentifier
        let appName = frontApp?.localizedName
        let cap = settings.maxHistoryItems
        let database = self.database
        let urlsToStore = viable

        // The "handled" decision is made on the main thread from the viable URL
        // list so the caller can skip the text/image fall-through immediately;
        // the byte copy + DB write run off-main so a multi-file Finder copy
        // cannot freeze the UI.
        captureQueue.async { [weak self] in
            var capturedAny = false
            for fileURL in urlsToStore {
                let attributes = try? FileManager.default.attributesOfItem(atPath: fileURL.path)
                let fileSize = (attributes?[.size] as? Int) ?? 0
                let displayName = fileURL.lastPathComponent

                do {
                    var mediaFilename: String? = nil
                    var storedByteSize: Int = fileSize

                    if fileSize <= thresholdBytes {
                        // Copy bytes into the media store.
                        let stored = try database.media.storeFile(at: fileURL)
                        mediaFilename = stored.mediaFilename
                        storedByteSize = stored.byteSize
                    }

                    var clip = Clip(
                        id: nil,
                        contentText: displayName,
                        contentRTF: nil,
                        contentHTML: nil,
                        typeIdentifier: "public.file-url",
                        sourceAppBundleID: bundleID,
                        sourceAppName: appName,
                        createdAt: Date(),
                        contentKind: .file,
                        mediaFilename: mediaFilename,
                        byteSize: storedByteSize
                    )
                    clip.filePath = fileURL.path

                    try database.saveCapturedFileClip(&clip, cap: cap)
                    capturedAny = true
                } catch {
                    ClippyLog.error("Failed to save file clip: \(error)", category: ClippyLog.capture)
                }
            }
            if capturedAny {
                DispatchQueue.main.async { [weak self] in self?.playCaptureSound() }
            }
        }
        // Return true whenever viable file URLs were on the pasteboard, even if
        // every save threw, so the caller does not fall through to text/image
        // capture and create a spurious filename text clip. Mirrors the legacy
        // single-file behavior of treating "file URLs present" as "handled".
        return true
    }

    // MARK: - Image capture

    /// Images are captured only when the pasteboard carries no text: a copied
    /// picture, a screenshot, not a rich-text snippet that happens to embed one.
    /// Returns true when the image was handled: captured, or rejected on purpose
    /// for exceeding the size cap. False means no image data was on the
    /// pasteboard, which the caller treats as "not filled in yet".
    @discardableResult
    private func captureImageIfPresent(from frontApp: NSRunningApplication?) -> Bool {
        guard AppSettings.shared.captureImages,
              let pngData = Self.pngData(from: pasteboard)
        else { return false }
        guard pngData.count <= AppSettings.shared.maxImageSizeMB * 1_048_576 else { return true }

        // Decode the pasteboard to PNG on the main thread (AppKit image path),
        // then dispatch the file write + DB insert off-main so a screenshot
        // capture cannot block the UI.
        let bundleID = frontApp?.bundleIdentifier
        let appName = frontApp?.localizedName
        let createdAt = Date()
        let cap = AppSettings.shared.maxHistoryItems
        let database = self.database

        captureQueue.async { [weak self] in
            do {
                let stored = try database.media.store(pngData: pngData)
                var clip = Clip(
                    id: nil,
                    contentText: "",
                    contentRTF: nil,
                    contentHTML: nil,
                    typeIdentifier: "public.png",
                    sourceAppBundleID: bundleID,
                    sourceAppName: appName,
                    createdAt: createdAt,
                    contentKind: .image,
                    mediaFilename: stored.mediaFilename,
                    thumbFilename: stored.thumbFilename,
                    pixelWidth: stored.pixelWidth,
                    pixelHeight: stored.pixelHeight,
                    byteSize: stored.byteSize
                )
                try database.saveCapturedImageClip(&clip, cap: cap)
                DispatchQueue.main.async { [weak self] in self?.playCaptureSound() }
            } catch {
                ClippyLog.error("Failed to save image clip: \(error)", category: ClippyLog.capture)
            }
        }
        return true
    }

    // MARK: - Sound feedback

    private func playCaptureSound() {
        let s = AppSettings.shared
        // Fire the menu bar mascot bounce on the same event so icon and sound
        // are perfectly in sync, whether or not the sound itself is enabled.
        NotificationCenter.default.post(name: .clippyDidCapture, object: nil)
        guard s.captureSoundEnabled else { return }
        SoundPlayer.play(id: s.captureSoundID, volume: SoundPlayer.sliderToVolume(s.captureSoundVolume))
    }

    private static func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff) else { return nil }
        // TIFF is rarely more than ~4x the eventual PNG; skip decoding clearly-over-cap data.
        guard tiff.count <= AppSettings.shared.maxImageSizeMB * 4_194_304 else { return nil }
        guard let image = NSImage(data: tiff) else { return nil }
        return MediaStore.pngData(from: image)
    }
}
