import AppKit
import Combine

extension Notification.Name {
    /// Posted on the main thread immediately after a clip is saved, at the same
    /// instant the capture sound fires. The status item observes it to bounce
    /// the mascot in sync with the sound.
    static let clippyDidCapture = Notification.Name("ClippyDidCapture")
}

/// Watches NSPasteboard.general by polling changeCount (the only supported
/// detection mechanism on macOS) and stores new items.
final class ClipboardMonitor {
    private let database: ClipDatabase
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount = 0
    private var skipNextChange = false
    private var cancellables = Set<AnyCancellable>()

    var isPaused = false

    /// Pasteboard types that mean "do not record this". ConcealedType is the
    /// convention password managers (1Password, Bitwarden, ...) set on copied
    /// secrets; TransientType marks ephemeral writes.
    private static let skippedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init(database: ClipDatabase) {
        self.database = database
    }

    // MARK: - Timer and polling

    func start() {
        lastChangeCount = pasteboard.changeCount
        scheduleTimer()
        AppSettings.shared.$pollingIntervalMs
            .removeDuplicates()
            .dropFirst()
            .sink { [weak self] _ in self?.scheduleTimer() }
            .store(in: &cancellables)
    }

    /// Called right before Clippy writes the pasteboard itself, so its own
    /// paste does not get re-captured (keeps history order stable).
    func ignoreNextChange() {
        skipNextChange = true
    }

    private func scheduleTimer() {
        timer?.invalidate()
        let interval = max(0.05, AppSettings.shared.pollingIntervalMs / 1000.0)
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
        timer.tolerance = interval / 4
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func tick() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        if skipNextChange {
            skipNextChange = false
            return
        }
        guard !isPaused else { return }
        captureCurrentPasteboard()
    }

    // MARK: - Text capture

    private func captureCurrentPasteboard() {
        guard let types = pasteboard.types, !types.isEmpty else { return }
        guard Self.skippedTypes.isDisjoint(with: Set(types)) else { return }

        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier,
           AppSettings.shared.ignoredBundleIDs.contains(bundleID) {
            return
        }

        // File URLs must be checked before the text path: Finder's copy puts
        // both a file URL and a display-name string on the pasteboard, and we
        // want the richer file clip, not a bare filename text clip.
        if captureFileIfPresent(from: frontApp) { return }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            captureText(text, from: frontApp)
            return
        }
        captureImageIfPresent(from: frontApp)
    }

    private func captureText(_ text: String, from frontApp: NSRunningApplication?) {
        let rtf = pasteboard.data(forType: .rtf)
        let html = pasteboard.data(forType: .html)
        let typeIdentifier: String
        if rtf != nil {
            typeIdentifier = "public.rtf"
        } else if html != nil {
            typeIdentifier = "public.html"
        } else {
            typeIdentifier = "public.utf8-plain-text"
        }

        var clip = Clip(
            id: nil,
            contentText: text,
            contentRTF: rtf,
            contentHTML: html,
            typeIdentifier: typeIdentifier,
            sourceAppBundleID: frontApp?.bundleIdentifier,
            sourceAppName: frontApp?.localizedName,
            createdAt: Date()
        )
        do {
            try database.saveCapturedClip(&clip, cap: AppSettings.shared.maxHistoryItems)
            // Sound fires only after a confirmed save; duplicates or DB errors
            // get no feedback. NSSound.play() is async and never blocks here.
            playCaptureSound()
            maybeAutoSuggestTitle(forText: text, clipID: clip.id)
        } catch {
            ClippyLog.error("Failed to save clip: \(error)", category: ClippyLog.capture)
        }
    }

    /// The one auto-applied agentic action: when enabled, give a freshly captured
    /// text clip an AI-suggested title. Opt-in, detached, and best-effort, so it
    /// never blocks or breaks capture; the title is still user-editable.
    private func maybeAutoSuggestTitle(forText text: String, clipID: Int64?) {
        let settings = AppSettings.shared
        guard settings.aiEnabled, settings.aiAutoSuggestTitles, let clipID else { return }
        guard case .success(let service) = AIService.fromSettings() else { return }
        let database = self.database
        Task.detached {
            // Title the exact row we just inserted. Re-finding by content text
            // could match a different clip when identical text was captured twice.
            guard let proposal = try? await service.suggestTitle(forText: text),
                  !proposal.proposed.isEmpty
            else { return }
            try? database.updateClipTitle(id: clipID, userTitle: proposal.proposed)
        }
    }

    // MARK: - File capture

    /// Returns true when at least one file clip was captured so the caller can
    /// skip text/image. Multi-file Finder selections are captured as one clip
    /// per file URL (mirroring how single-file clips are saved), so a Cmd+C of
    /// five files produces five file clips in history rather than silently
    /// keeping only the first URL.
    @discardableResult
    private func captureFileIfPresent(from frontApp: NSRunningApplication?) -> Bool {
        let settings = AppSettings.shared
        guard settings.captureFiles else { return false }

        let options: [NSPasteboard.ReadingOptionKey: Any] = [
            .urlReadingFileURLsOnly: true
        ]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options)
                as? [URL],
              !urls.isEmpty
        else { return false }

        // Filter out zero-byte / unreadable files up front so one bad file in a
        // multi-selection does not abort the whole capture. A single empty file
        // (the legacy behavior) still returns false here so the caller can fall
        // through to text/image capture.
        let viable = urls.filter { url in
            let attrs = try? FileManager.default.attributesOfItem(atPath: url.path)
            let size = (attrs?[.size] as? Int) ?? 0
            return size > 0
        }
        guard !viable.isEmpty else { return false }

        let thresholdBytes = settings.maxFileSizeMB * 1_000_000
        var capturedAny = false
        for fileURL in viable {
            let attributes = try? FileManager.default.attributesOfItem(atPath: fileURL.path)
            let fileSize = (attributes?[.size] as? Int) ?? 0
            let displayName = fileURL.lastPathComponent

            do {
                var mediaFilename: String? = nil
                var storedByteSize: Int = fileSize

                if fileSize <= thresholdBytes {
                    // Copy bytes into the media store.
                    let stored = try database.media.storeFile(at: fileURL)
                    mediaFilename = stored.mediaFilename
                    storedByteSize = stored.byteSize
                }

                var clip = Clip(
                    id: nil,
                    contentText: displayName,
                    contentRTF: nil,
                    contentHTML: nil,
                    typeIdentifier: "public.file-url",
                    sourceAppBundleID: frontApp?.bundleIdentifier,
                    sourceAppName: frontApp?.localizedName,
                    createdAt: Date(),
                    contentKind: .file,
                    mediaFilename: mediaFilename,
                    byteSize: storedByteSize
                )
                clip.filePath = fileURL.path

                try database.saveCapturedFileClip(&clip, cap: settings.maxHistoryItems)
                capturedAny = true
            } catch {
                ClippyLog.error("Failed to save file clip: \(error)", category: ClippyLog.capture)
            }
        }
        if capturedAny {
            playCaptureSound()
        }
        // Return true whenever viable file URLs were on the pasteboard, even if
        // every save threw, so the caller does not fall through to text/image
        // capture and create a spurious filename text clip. Mirrors the legacy
        // single-file behavior of treating "file URLs present" as "handled".
        return true
    }

    // MARK: - Image capture

    /// Images are captured only when the pasteboard carries no text: a copied
    /// picture, a screenshot, not a rich-text snippet that happens to embed one.
    private func captureImageIfPresent(from frontApp: NSRunningApplication?) {
        guard AppSettings.shared.captureImages,
              let pngData = Self.pngData(from: pasteboard)
        else { return }
        guard pngData.count <= AppSettings.shared.maxImageSizeMB * 1_048_576 else { return }

        do {
            let stored = try database.media.store(pngData: pngData)
            var clip = Clip(
                id: nil,
                contentText: "",
                contentRTF: nil,
                contentHTML: nil,
                typeIdentifier: "public.png",
                sourceAppBundleID: frontApp?.bundleIdentifier,
                sourceAppName: frontApp?.localizedName,
                createdAt: Date(),
                contentKind: .image,
                mediaFilename: stored.mediaFilename,
                thumbFilename: stored.thumbFilename,
                pixelWidth: stored.pixelWidth,
                pixelHeight: stored.pixelHeight,
                byteSize: stored.byteSize
            )
            try database.saveCapturedImageClip(&clip, cap: AppSettings.shared.maxHistoryItems)
            playCaptureSound()
        } catch {
            ClippyLog.error("Failed to save image clip: \(error)", category: ClippyLog.capture)
        }
    }

    // MARK: - Sound feedback

    private func playCaptureSound() {
        let s = AppSettings.shared
        // Fire the menu bar mascot bounce on the same event so icon and sound
        // are perfectly in sync, whether or not the sound itself is enabled.
        NotificationCenter.default.post(name: .clippyDidCapture, object: nil)
        guard s.captureSoundEnabled else { return }
        SoundPlayer.play(id: s.captureSoundID, volume: SoundPlayer.sliderToVolume(s.captureSoundVolume))
    }

    private static func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff) else { return nil }
        // TIFF is rarely more than ~4x the eventual PNG; skip decoding clearly-over-cap data.
        guard tiff.count <= AppSettings.shared.maxImageSizeMB * 4_194_304 else { return nil }
        guard let image = NSImage(data: tiff) else { return nil }
        return MediaStore.pngData(from: image)
    }
}
